[package]
name = "systools-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
# Crate to aid testing by placing built binaries on the path.
assert_cmd = "2.0.0"

# [[bin]]
# name = "true"
# path = "src/bin/true.rs"

# [[bin]]
# name = "false"
# path = "src/bin/false.rs"
